/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-300": "#9d4edd",
        "primary-500": "#5a189a",
        "primary-600": "#3c096c",
        "primary-700": "#240046",
        "secondary-300": "#c75146",
        "secondary-500": "#ad2e24",
        "secondary-600": "#81171b",
        "secondary-700": "#540804",
        "tertiary-300": "#ffc300",
        "tertiary-500": "#ffaa00",
        "tertiary-600": "#ff9500",
        "tertiary-700": "#ff7b00",
        // "primary-300-dark": "var(--color-primary-300-dark)",
        // "primary-500-dark": "var(--color-primary-500-dark)",
        // "primary-600-dark": "var(--color-primary-600-dark)",
        // "primary-700-dark": "var(--color-primary-700-dark)",
        // "secondary-300-dark": "var(--color-secondary-300-dark)",
        // "secondary-500-dark": "var(--color-secondary-500-dark)",
        // "secondary-600-dark": "var(--color-secondary-600-dark)",
        // "secondary-700-dark": "var(--color-secondary-700-dark)",
        // "tertiary-300-dark": "var(--color-tertiary-300-dark)",
        // "tertiary-500-dark": "var(--color-tertiary-500-dark)",
        // "tertiary-600-dark": "var(--color-tertiary-600-dark)",
        // "tertiary-700-dark": "var(--color-tertiary-700-dark)",
        // "alert-300": "var(--color-red-300)",
        // "alert-500": "var(--color-red-500)",
        // "success-300": "var(--color-success-300)",
        // "success-500": "var(--color-success-500)",
        // "warning-300": "var(--color-warning-300)",
        // "warning-500": "var(--color-warning-500)",
      },
      // now the font sizes
      fontSize: {
        "normal-content-size": "1rem",
        "large-content-size": "1.125rem",
        "label-size": "0.875rem",
        "main-title-size": "2rem",
        "secondary-title-size": "1.5rem",
        "tertiary-title-size": "1.25rem",
        "input-size": "1.15rem",
      },
      // the breakpoints
      screens: {
        mobile: "435px",
        tablet: "768px",
        laptop: "1024px",
        desktop: "1440px",
      },
    },
  },
  plugins: [],
};
