/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        "primary-300": "var(--color-primary-300)",
        "primary-500": "var(--color-primary-500)",
        "primary-600": "var(--color-primary-600)",
        "primary-700": "var(--color-primary-700)",
        "secondary-300": "var(--color-secondary-300)",
        "secondary-500": "var(--color-secondary-500)",
        "secondary-600": "var(--color-secondary-600)",
        "secondary-700": "var(--color-secondary-700)",
        "tertiary-300": "var(--color-tertiary-300)",
        "tertiary-500": "var(--color-tertiary-500)",
        "tertiary-600": "var(--color-tertiary-600)",
        "tertiary-700": "var(--color-tertiary-700)",
        "primary-300-dark": "var(--color-primary-300-dark)",
        "primary-500-dark": "var(--color-primary-500-dark)",
        "primary-600-dark": "var(--color-primary-600-dark)",
        "primary-700-dark": "var(--color-primary-700-dark)",
        "secondary-300-dark": "var(--color-secondary-300-dark)",
        "secondary-500-dark": "var(--color-secondary-500-dark)",
        "secondary-600-dark": "var(--color-secondary-600-dark)",
        "secondary-700-dark": "var(--color-secondary-700-dark)",
        "tertiary-300-dark": "var(--color-tertiary-300-dark)",
        "tertiary-500-dark": "var(--color-tertiary-500-dark)",
        "tertiary-600-dark": "var(--color-tertiary-600-dark)",
        "tertiary-700-dark": "var(--color-tertiary-700-dark)",
        "alert-300": "var(--color-alert-300)",
        "alert-500": "var(--color-alert-500)",
        "success-300": "var(--color-success-300)",
        "success-500": "var(--color-success-500)",
        "warning-300": "var(--color-warning-300)",
        "warning-500": "var(--color-warning-500)",
      },
    },
  },
  plugins: [],
};
